name: Releases

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: 16.x

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip libudev-dev libusb-1.0-0-dev

      - name: Install node modules
        run: npm ci

      - name: Build Web
        run: npm run build

      - name: Zip release
        run: cd dist && zip -r web.zip web

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/web.zip
