name: Test

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: 16.x

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip libudev-dev libusb-1.0-0-dev

      - name: Install node modules
        run: npm ci

      - name: Run tests
        run: npm run test
